### ISSUE TITLE
Открытие окна при загрузке страницы.

### ISSUE THREAD

**Issue by zhukov-ivan** [maxdenaro/graph-modal#9]
Добрый день. Как я могу вызвать окно при загрузке страницы по определенному .hash:

```
window.addEventListener('load', function () {
  const hash = window.location.hash;
  
  if(hash == '#serv-order'){
// Что необходимо вставить если data-graph-target="serv-order" ?
  }
})
```

Спасибо

**Comment by maxdenaro** [comment]
Добрый день. Посмотрите тут: https://github.com/maxdenaro/graph-modal#%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BD%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BE%D0%BA%D0%BD%D0%B0-%D0%BF%D0%BE-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8E

**Comment by zhukov-ivan** [comment]
Да, я смотрел. Но new GraphModal().open('serv-order'); ничего не дает. А в консоли выдает ошибку Uncaught ReferenceError: GraphModal is not defined

**Comment by maxdenaro** [comment]
Ну это значит что вы не подключили библиотеку вовсе

**Comment by zhukov-ivan** [comment]
Спасибо! Я использовал в gulp сборке вашу библиотеку, подключил в package.json "graph-modal": "^1.0.6", она работает корректно, окна отображаются и всплывают, но new GraphModal().open('serv-order'); не работает. Подключил graph-modal.min.js отдельным файлом уже в build проект и тогда заработало. Думал что new GraphModal().open('serv-order'); должно и без подключения graph-modal.min.js работать.
